# docker-compose.yml
version: "3"
services:
  app:
    container_name: forfeater-nodejs
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
  postgres:
    image: postgres:9.6.8-alpine
    environment:
      POSTGRES_PASSWORD: postgres
